config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root to: 'home#index'
  resources :users, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @current_user = User.find(params[:id])
  end

  def edit
    @current_user = User.find(params[:id])
  end

  def update
    @current_user = User.find(params[:id])
    @current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website,
                               :bio, :email, :phone, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instuigram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="#">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Instagram
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
          <% if user_signed_in? %>
            <a href="<%= user_path(current_user)%>">
              <i class="fa fa-user"></i>
            </a>
          <% else %>
            <a href="<%= new_user_session_path%>">
              <i class="fa fa-sign-in"></i>
            </a>
          <% end %>
	</div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US
          </li>
          <li>SUPPORT</li>
          <li>PRESS</li>
          <li>API</li>
          <li>JOBS</li>
          <li>PRIVACY</li>
          <li>TERMS</li>
          <li>DIRECTORY</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2018 INSTAGRAM </p>
      </nav>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with model: @current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
  <div class="form-group row">
    <div class="col-sm-3 col-form-label">
      <img class="avatar" src="https://www.rollingstone.com/wp-content/uploads/2018/06/avicii-interview-rolling-stone-91816b43-19e9-4ef2-8a1e-857428f69960.jpg?crop=900:600&width=440">
    </div>
    <div class="col-sm-9">
      <p class="username"><%=current_user.username %></p>
      <a class="change-photo" href="">Change Profile Photo</a>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :name, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :username, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :username, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :website, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :website, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_area :bio, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :email, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
    <div class="col-sm-9">
      <%= f.text_field :gender, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-3">
    </div>
    <div class="col-sm-9">
      <%= f.submit "Submit", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0x4J2SmvFTYvCHk4yNWRdsc_g42_r9mBhlyy8RCWjazpIysTz9w">
      </div>
    </div>
   <div class="col-md-8 basic-info">
    <div class="user-wrapper">
      <h2 class="username"><%= current_user.username %></h2>
      <a class="edit-profile" href="">
    <button>Edit Profile</button>
    </a>
      </div>
      <ul class="posts">
        <li><span>12</span> posts</li>
        <li><span>195</span> followers</li>
        <li><span>345</span> following</li>
      </ul>
	   <h2 class="name"><%= current_user.name %></h2>
	  <%=link_to current_user.website, current_user.website, class:  'website' %>
    </div>
   </div>
  </div>
</div>
<div class="user-tabs">
  <a class="tab active" href="">
    <i class="fa fa-th"></i>
    POSTS
  </a>
  <a class="tab" href="">
    <i class="fa fa-tv"></i>
    IGTV
  </a>
  <a class="tab" href="">
    <i class="fa fa-bookmark"></i>
    SAVED
  </a>
  <a class="tab" href="">
    <i class="fa fa-tag"></i>
    TAGGED
  </a>
</div>
<div class="user-images">
  <div class="wrapper">
    <img src="https://www.rollingstone.com/wp-content/uploads/2018/06/avicii-interview-rolling-stone-91816b43-19e9-4ef2-8a1e-857428f69960.jpg?crop=900:600&width=440">
  </div>
  <div class="wrapper">
    <img src="https://www.rollingstone.com/wp-content/uploads/2018/06/avicii-interview-rolling-stone-91816b43-19e9-4ef2-8a1e-857428f69960.jpg?crop=900:600&width=440">
  </div>
  <div class="wrapper">
    <img src="https://www.rollingstone.com/wp-content/uploads/2018/06/avicii-interview-rolling-stone-91816b43-19e9-4ef2-8a1e-857428f69960.jpg?crop=900:600&width=440">
  </div>
</div>